name: Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Infrastructure Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template--initial-infra.yaml \
            --stack-name infrastructure-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Output Infrastructure Stack Info
        run: |
          aws cloudformation describe-stacks \
            --stack-name infrastructure-stack \
            --query "Stacks[0].Outputs" \
            > infrastructure-outputs.json
          cat infrastructure-outputs.json

      - name: Upload infrastructure outputs to S3
        env:
          BUCKET_NAME: "expensetrackerinfra-shravan"
        run: |
          set -e

          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket exists: $BUCKET_NAME"
          else
            echo "Creating bucket: $BUCKET_NAME"
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region $AWS_REGION \
              --create-bucket-configuration LocationConstraint=$AWS_REGION
          fi

          aws s3 cp infrastructure-outputs.json s3://$BUCKET_NAME/infrastructure-outputs.json
